# Generated by Django 4.2 on 2024-11-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_publicacion_autor_alter_publicacion_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'permissions': (('add.publicacion', 'Puede agregar publicaciones'), ('change.publicacion', 'Puede cambiar publicaciones'), ('delete.publicacion', 'Puede borrar publicaciones'))},
        ),
    ]
