# Generated by Django 4.2 on 2024-11-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_publicacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'permissions': (('addPublicacion', 'Puede agregar publicaciones'), ('changePublicacion', 'Puede cambiar publicaciones'), ('deletePublicacion', 'Puede borrar publicaciones'), ('viewPublicacion', 'Puede ver una Publicacion'))},
        ),
    ]
