# Generated by Django 4.2 on 2024-11-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_publicacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={},
        ),
    ]
